version: '3.8'

services:
  suppliers-web:
    build:
      context: ./services/suppliers-ms
      dockerfile: docker/web/Dockerfile
    container_name: suppliers-web
    environment:
      SERVICE_NAME: SUPPLIERS-MS
      PORT: 3001
      # inside the compose network, talk to Kafka by its service name/port
      KAFKA_BROKERS: kafka:29092
      KAFKA_CLIENT_ID: suppliers-ms
    ports:
      - "3001:3001"
    depends_on:
      - kafka

  suppliers-worker:
    build:
      context: ./services/suppliers-ms
      dockerfile: docker/worker/Dockerfile
    container_name: suppliers-worker
    environment:
      SERVICE_NAME: SUPPLIERS-MS-WORKER
      KAFKA_BROKERS: kafka:29092
      KAFKA_CLIENT_ID: suppliers-ms-worker
      KAFKA_GROUP_ID: suppliers-worker-group
      # IMPORTANT: match the topic your web publishes to
      KAFKA_TOPICS: supplier-events
    depends_on:
      - kafka

  purchase-plans-worker:
    build:
      context: ./services/purchase-plans-ms
      dockerfile: docker/worker/Dockerfile
    container_name: purchase-plans-worker
    environment:
      SERVICE_NAME: PURCHASE-PLANS-MS-WORKER
      KAFKA_BROKERS: kafka:29092
      KAFKA_CLIENT_ID: purchase-plans-ms-worker
      KAFKA_GROUP_ID: purchase-plans-worker-group
      KAFKA_TOPICS: supplier-events
      DDB_TABLE: purchase-plans-db
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_ENDPOINT_URL_DYNAMODB: http://dynamodb-local:8000
    depends_on:
      - kafka
      - dynamodb-local

  contracts-worker:
    build:
      context: ./services/contracts-ms
      dockerfile: docker/worker/Dockerfile
    container_name: contracts-worker
    environment:
      SERVICE_NAME: CONTRACTS-MS-WORKER
      KAFKA_BROKERS: kafka:29092
      KAFKA_CLIENT_ID: contracts-ms-worker
      KAFKA_GROUP_ID: contracts-worker-group
      KAFKA_TOPICS: supplier-events
      DDB_TABLE: contracts-db
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_ENDPOINT_URL_DYNAMODB: http://dynamodb-local:8000
    depends_on:
      - kafka
      - dynamodb-local